name: Notificacao Discord

on: [push]

jobs:
    git:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
    
        - name: Run Discord Webhook
          uses: Sniddl/discord-commits@v1.6
          with:
            webhook: ${{ secrets.WEBHOOK_DISCORD }}
